package kind;


public enum Action {
    BUILD_GARAGE,
    BUILD_FIRE_STATION,
    BUILD_FOWL_HOUSE,
    BUILD_LABORATORY,
    BUILD_PIGPEN,
    BUY_FIELD,
    FINISH_TURN,
    HARVEST,
    INVEST_FIRE_EXTINGUISHER,
    INVEST_FIRE_PLUG,
    INVEST_INCUBATOR,
    INVEST_MICROSCOPE,
    INVEST_THRESHING_MACHINE,
    INVEST_TRACTOR,
    PLANT_BARLEY,
    PLANT_CORN,
    PLANT_OATS,
    PLANT_RICE,
    PLANT_WHEAT,
    SELL_CROP,
    INVALID_ACTION, // Technical...
}
