package kind;

public enum Permission {

    DECREASE_INFECTION_CHANCE_2,
    DECREASE_INFECTION_CHANCE_3,
    DECREASE_FIRE_CHANCE,
    INVEST_ESTINGUISHER,
    INVEST_MACHINES,
    PLANT_MULTIPLE_FIELDS,
    RESEARCH,
}
